// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdAvDiHEwLGf0i2irvxBMMI7Gv4D4oyOA',
    appId: '1:64874623717:web:f748ab603e635f9c041a0c',
    messagingSenderId: '64874623717',
    projectId: 'smart-budget-app-60caf',
    authDomain: 'smart-budget-app-60caf.firebaseapp.com',
    databaseURL: 'https://smart-budget-app-60caf-default-rtdb.firebaseio.com',
    storageBucket: 'smart-budget-app-60caf.firebasestorage.app',
    measurementId: 'G-0JW7YKYPHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNp8vMYROd-3KVN-4VEfVl2F0i_6SZ7-4',
    appId: '1:64874623717:android:e9c03d8f4f2edd5c041a0c',
    messagingSenderId: '64874623717',
    projectId: 'smart-budget-app-60caf',
    databaseURL: 'https://smart-budget-app-60caf-default-rtdb.firebaseio.com',
    storageBucket: 'smart-budget-app-60caf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkXyp66bUvKjrmh4v3rlhlB3RKFn_v9XA',
    appId: '1:64874623717:ios:f640be42f5ceeeea041a0c',
    messagingSenderId: '64874623717',
    projectId: 'smart-budget-app-60caf',
    databaseURL: 'https://smart-budget-app-60caf-default-rtdb.firebaseio.com',
    storageBucket: 'smart-budget-app-60caf.firebasestorage.app',
    iosBundleId: 'com.example.smartBudgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkXyp66bUvKjrmh4v3rlhlB3RKFn_v9XA',
    appId: '1:64874623717:ios:f640be42f5ceeeea041a0c',
    messagingSenderId: '64874623717',
    projectId: 'smart-budget-app-60caf',
    databaseURL: 'https://smart-budget-app-60caf-default-rtdb.firebaseio.com',
    storageBucket: 'smart-budget-app-60caf.firebasestorage.app',
    iosBundleId: 'com.example.smartBudgetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdAvDiHEwLGf0i2irvxBMMI7Gv4D4oyOA',
    appId: '1:64874623717:web:a8aa69b63dae4a6f041a0c',
    messagingSenderId: '64874623717',
    projectId: 'smart-budget-app-60caf',
    authDomain: 'smart-budget-app-60caf.firebaseapp.com',
    databaseURL: 'https://smart-budget-app-60caf-default-rtdb.firebaseio.com',
    storageBucket: 'smart-budget-app-60caf.firebasestorage.app',
    measurementId: 'G-TLQ7EFXKE0',
  );
}
